name: Snyk Security

on:
  workflow_dispatch:

jobs:
  snyk_scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out main branch
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Cache Snyk
      id: cache-snyk
      uses: actions/cache@v4
      env:
        cache-name: cache-snyk
      with:
        path: ~/snyk
        key: ${{ runner.os }}-snyk

    - if: ${{ steps.cache-snyk.outputs.cache-hit != 'true' }}
      name: Install Snyk CLI
      run: |
        curl https://static.snyk.io/cli/latest/snyk-linux -o ~/snyk
        chmod +x ~/snyk

    - name: Snyk scan
      continue-on-error: true
      run: |
        dotnet build
        ~/snyk auth ${{ secrets.SNYK_TOKEN }}
        ~/snyk config set org=3b6229b4-e0fe-405e-8283-ac41405bf85c
        ~/snyk test --all-projects || true
        ~/snyk monitor --all-projects || true
        ~/snyk code test --report --project-name="WebGoat.NET" || true
        
